name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [react, solidjs, vue, qwik, svelte, lit, preact] 
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build Core
        run: cd packages/core && bun run build

      - name: Build package
        run: cd packages/${{ matrix.project }} && bun run build

      - name: Install package dependencies
        run: bun install

      - name: Install Playwright Browsers
        run: cd packages/${{ matrix.project }} && bunx playwright install --with-deps

      - name: Run Playwright tests
        run: cd packages/${{ matrix.project }} && bunx playwright test

      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.project }}
          path: packages/${{ matrix.project }}/playwright-report/
          retention-days: 30